### PR TITLE
account_asset_managements: tests and huge performance improvements

### PR DESCRIPTION
**Pull request by sbidoul**
Hi Luc,

Here is a significant performance improvement which is much necessary to handle a large amount of assets (~1000).

It reduces the number of SQL requests by several orders of magnitude when recomputing the depreciation values in parent assets.

Plus a basic test suite.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@sbidoul 
I don't know the  'conflicts' keyword in the **openerp**.py manifest. 
Is this a new convention ?

**Comment by sbidoul** [comment]
@luc-demeyer conflicts was discussed on the community list a while ago. It's just a convention so far, with the hope the system will enforce it at some point in the future.

**Comment by luc-demeyer** [comment]
Merged.

**Comment by sbidoul** [comment]
Thanks for merging, Luc! Next time it would be great if you could merge using the merge button so as to preserve commit authorship and the commit history. Having small commits makes it easier to understand the history.

**Pull request closed without merging**
