### PR TITLE
Allow to remove an asset before its full depreciation

### PR DESCRIPTION
**Pull request by florian-dacosta**
The changes : 
- New account on asset category, used only when we remove an asset before it is fully depreciated
- add a button when an asset is opened to allow the antipated removal

If the user choose to do so, it will remove all depreciation lines which date is after the removal  date.
It will change the depreciation line corresponding to the removal date to adjust the amount and the date if we the boolean 'prorata temporis' is matched. (Else, it will remove it). Then validate automaticaly this modified depreciation line so it creates its account.move.line.
Finally, it will creates 3 removal account move line. The residual amount which could not be depreciated goes to the new account.

Note, the early removal date have to be after the last posted entry and during the first non-posted entry.

I make a merge proposal here so you can tell me what you think and ask if it is not clear.
I would gladly take your advices into consideration.
If you think merging this PR with yours would delay the merge into OCA branch, then I can propose this merge to OCA directly so it won't impact your PR.

Anyway, I would like to have your opinion.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
Florian,

Thanks for this contribution. 

Adding such a feature is a great improvement for this module, hence let’s go for it.

I think though that we need a bit more discussion with the finance expert community before merging this.

Some thoughts:

I don’t like the parameter on the asset category for this case, since you can’t catch all situations in a single extra general account or a 3 lines accounting move.

Consider the following case:

You have an asset of 100K, depreciated for 80K that you sell for 40K before the end of the asset life time.

In this case you have two transactions:

1)      Sales transaction, with 40K Credit on the ‘asset sale’ general account 

2)      Asset removal transaction with 4 lines:

```
                                                           i.      40K Debit on the ‘asset sale’ general account (reversal of sale transaction)

                                                         ii.      80K Debit on the ‘asset depreciation’ general account

                                                        iii.      20K Credit on the ‘asset plus-value’ general account

                                                       iv.      100K Credit on the ‘asset’ general account
```

There is also the scenario with min-values in stead of plus-values (in our country we use other general accounts for this) and there is another missing feature which is the asset revaluation during its lifecycle. 

What about the following idea for the ‘early asset removal’:

A button on an active asset pops up a prefilled unbalanced account move screen.

It’s prefilled with the reversal of the asset and asset depreciation general account (hence 80K and 100K in scenario above), but since that transaction is unbalanced in case of early removal, the customer will be obliged to add more lines and hence we cover all scenarios.

We also do not prefill the mandatory account move ‘date’ field so that the user can set the removal date (whereby we keep the controls you have already implemented). 

Upon exit of the pop-up screen, we set adjust the depreciation lines with the last line dated equal to the accounting entry.

I think it should be possible to use a similar scenario for revaluation during the asset life cycle (we can add this in a second phase) and we also need to think about the impact on reporting (the account_asset_management_xls module must be adapted to also reflect the plus and min values).

From a timing standpoint my preference goes to a merge into the financial tools of what we currently have (the 7.0 PR for the asset mgt and once this is done I’ll resubmit the 6.1 and 8.0 PR’s).

Looking to our customer projects and priorities, my preference is to implement the early removal feature first on 8.0.

Frédéric, Stéphane,

Since both of you are also testing this module, can you comment ? 

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by florian-dacosta** [comment]
Thank you for your reply.

You are right, it does not cover all the cases.
Originally, the idea was not to handle the case of a sale of the asset but rather a loss.
(robbery, breakdown, relocation of the company, etc...).

I like your idea, it is really more complete.
I'll try to go in that direction and let's see what Stéphane and Frédéric think about it. (Although I am not sure they will see the PR because it is not on the OCA repository).

**Comment by fclementic2c** [comment]
Hello and thanks for this contribution.

I just did a first test this morning and I could install it without any problems on a existing test DB...which is a good start. 
Here are the littles issues I saw :
- When I clicked on Generate Removal entries (after I clicked on Early Remval), I had a error : ProgrammingError: operator does not exist: integer = boolean
  It appears because I did not set the new account added with this MP. It would be good to catch this error (although it is a mandatory field)
- For clarity, it would be good to add a comment on this wizard to explain that the expected date must be right after the last posted depreciation entry
- On the history tab, I do not wee the move number : please add it as 1st column 
- When you duplicate an existing asset, in the history tab it should not duplicate the time methode history log (2nd M2N field at the bottom)
- Now I come to the main issue : After the asset removal, I see an extra line on the Depreciation Board with a type 'Asset removal' but the amount is wrong in my view since it should be equals to the sum of cumulated depreciation already posted so far...see print screen below



@luc-demeyer:  

It seems that in France and Belgium we have a little difference on the way assets removal entries are posted. On the accounting aspect it is very little but it will be much more work to make this functionality generic.

In short, in France there 1 account for the sale and 1 account for the residual value while in Belgium the 2 are compensated into either a gain or a loss. So In France we can post separately the 2 entries and in Belgium it seems that you cannot. 
(I can add that Switzerland is similare to Belgium on this point.)

For reférence:
France : http://unt.unice.fr/aunege/M2/compta_gen_Nancy2/co/ft10.html
Switzerland : http://www.lacompta.ch/lacompta_cake/contents/view/25
SAP : http://help.sap.com/saphelp_46c/helpdata/en/4f/71e946448011d189f00000e81ddfac/content.htm

@ florian : it seems that in order to be generic we need 2 accounts instead of 1 (one in case of seeling price > residual value (gain) and  in case of seeling price < residual value (loss). For France, we will always put the same account in both field. 

What dou you think ?

Frederic

**Comment by florian-dacosta** [comment]
Thanks for your review.
Regarding the issues, I will fix it as soon as we agree on a solution.

So finally could it be this way : 
- Add  2 accounts on the category (maybe the one for loss required and the one for plus-value optional)
- If the reason of removal is a sale, in this case, the user should have linked the invoice line to the asset beforehand.

Then when we click on the remove button, it will create all accounting moves.
If the reason of the removal is just a loss (immobilisation broken, etc...), we do not change anything, we have 3 account.move.line, using the loss account.

If the reason of removal is a sale, we use the link with the account invoice line to get the sale amount and sale account. we create the 4 account move line. We use the plus value or loss account depending of the sale amount. 

This way I guess we can handle all the cases we talked about.

**Comment by luc-demeyer** [comment]
@florian-dacosta I am looking forward to test the code with the 2 additional accounts and the link to the sale invoice line.

**Comment by fclementic2c** [comment]
Hi Florian,

You say 'If the reason of removal is a sale, we use the link with the
account invoice line to get the sale amount and sale account. we create the
4 account move line. We use the plus value or loss account depending of the
sale amount'

If you do so, you will not cover the french use case where:
- the selling price has to be in the account 775 - Produits de cessions des
  éléments d'actifs
- the residual value has to be in the account 675 - Valeur nette comptable
  des éléments d'actif cédés
  The profit or the loss is the difference between these 2 accounts

For Belgium (and most of countries I think), you have to check first if it
is a gain or a loss (seeling price - residual value) and then use one or
the other.
Note : Don't forget that most of the time assets that you dispose are fully
depreciated and then you will have none of these 2 accounts to use

I agree that we need 2 buttons on the asset form : one for 'Disposal' and
on for 'Sale'

_camptocamp_

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Frédéric Clementi_
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com

2014-11-24 16:36 GMT+01:00 luc-demeyer notifications@github.com:

**Comment by florian-dacosta** [comment]
So, I have added an account for the case of plus value in Belgium and other countries.

We have 2 new accounts : 
-Residual Value Account : for the french way, it is the only one usefull for the early removal case.
It works the same as described before.
For the Belgium this account would match the loss account.
- The Plus-Value Account : it is used only for the Belgium case. (=> therefore it is not mandatory)

For the Belgium sale case, before doing the removal, you have to choose the asset on your customer invoice.
Once it is done, you can process the ealry removal.

If this solution works for all, I am thinking in maybe create a new group so we show the Plus-Value Account and the asset_id in customer invoice view only for the users of this group. This way this field wouldn't be visible for user who don't need them (like in France.)
Also, if it seems better for you, I could add a third account which would be the loss account in Belgium case, so only the residual account would be used in France and only the plus-value and loss account would be used in Belgium.
But I am not convinced it would be simpler this way for the user.

@fclementic2c : I have fixed all issues you have pointed out but one.  I tried to reproduce the bug on the amount, but I couldn't, it works fine here. Just note that the 2 amounts you show on your screenshot should not be equal. The amount of the removal line should be equal to the sum of the amount and amount already depreciated of the last depreciated line.
There still is a problem with your case. If you can tell me more about it, I may be able to find more about it.

**Comment by luc-demeyer** [comment]
@florian-dacosta , @fclementic2c 
I have built upon Florian's your work for the early asset removal to make it more generic and merged this into PR https://github.com/OCA/account-financial-tools/pull/51.

Changes compared to your PR:
- the extra asset accounts in the asset category are no longer required. They now serve as defaults for the asset removal wizard (and become required only when needed to support a specific case).
- I have introduced the concept of 'posting regimes' in order to support both the 'french' and the 'non-french' regimes. The regime is selected automatically based upon the company country.
- I replaced the groups="account_asset_management.account_asset_use_plusvalue" by "account.group_account_manager" since I don't we need this extra security layer.
- I merged the 'Set to Removed' and 'Early Removal' buttons into one 'Remove' button.
- I changed the '_prepare_early_removal' method to use the same logic for prorata and non prorata. If the logic has to be different, than we should discuss so that I understand it.
- I changed the sale invoice logic in order to handle asset sale both in case of normal and early removal. I also adapted the logic to support multi-currency and to allow an asset sale via multiple invoices.
- After the processing of the removal wizard, the generated accounting entry is opened so that the accountant can review the result and adjust when required.

**Comment by fclementic2c** [comment]
Many thanks Luc for this contribution.

We will probably need you module in v8 and my colleagues (beguining of
2015) will have the time to review/test/contribute on your work.

_camptocamp_

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

_Frédéric Clementi_
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com

2014-12-15 15:47 GMT+01:00 luc-demeyer notifications@github.com:

**Comment by florian-dacosta** [comment]
Thank you for your work.
2 comments right now : 
1) About your first changement, I see that the min value et plus value accounts are required in the category.
You seem to say that it should not (I agree), is it a mistake?
In the french case, it is a real problem to have these to accounts as required as, they won't be used.

2) I think that the field on the invoice won't ever be used for the french case, that's why it could be nice to hide it in this case. That is  why I had added a group for this field, not for a matter of security. I am not sure of the right solution to hide it properly.

Otherwise, it seems very nice to me, I will test it very soon

**Comment by luc-demeyer** [comment]
@florian-dacosta 
1) This is bug (which I corrected in the meanwhile together with a correction of the residual_value calculation to take into account the early removal. 
Hence you should download the last version before starting your tests.

2) I think that also in the 'french' case it could be useful to keep this field. One of the things that I have in mind is a wizard that pops up when filling in the asset_id on a sales invoice line. That wizard will propose to generate the asset removal entries.
If you don't like the idea of such a wizard, than I suggest to hide/show the field based upon the 'Posting Regime'. This will ensure correct functioning in a multi-company environment (hide/show the field will depend on the country code).
@fclementic2c , @sbidoul 
Frédéric, Stéphane : what do you think about the idea of a removal wizard on sale invoice ?

**Pull request closed without merging**
