### PR TITLE
7.0 asset management additional improvements

### PR DESCRIPTION
**Pull request by sbidoul**
- more tests
- support depreciation account moves with depreciations with different assets in the same move (such moves are not generated by the module but may occur when migrating data from other systems)
- support situations where we have init entries in the same FY as actual depreciation moves

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@sbidoul 
Some feedback:
1)  More tests are always great. Thanks a lot.
2)  I had a quick look to the diff for the other improvements. I am not sure it's good idea to go on this path. I actually intended to remove the code that retreives the data from the accounting entries in stead of from the depreciation lines since there are controls now in the code to ensure that the accounting move is equal to the depreciation line. The code will become simpler to read and to maintain (this piece of code is a left-over of older work we have done in the past to get the asset module working). Any deviation between historically posted accounting entries and the table can be resolved by manually editing the calculated table (adjust amount & date and set the init flag). In case of many entries, 'manually' becomes of course a script. 
I have done a couple of exercises already and so far I haven't encountered a situation where I could not align the tables with the legacy accounting entries.
I propose that we setup a skype call (or google hangout) so that we can share screens in case you have situations that are not covered.

**Comment by sbidoul** [comment]
Hi @luc-demeyer,

The main situation that I need to cover is demonstrated in test_4:
- an asset starting in july 2014
- an init entry on 30/11/2014
- computing the depreciation board gives wrong results for 12/2014

That said I agree we can simplify the code by dropping the lookup for account moves and compute on depreciation lines lines only.

We can do a hangout. Let me know what time suits you best.

**Comment by sbidoul** [comment]
@luc-demeyer the change we discussed is in. Please review carefully (the test suite is green, but I'm not sure of its coverage).

**Comment by luc-demeyer** [comment]
code looks ok. I also performed a number of tests and everything work, hence PR is merged.
Thanks.

**Pull request merged**
